name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y gcc make libncurses5-dev

      - name: Build project
        run: make build
